server:
  port: 8761

eureka:
  server:
    renewal-percent-threshold: 0.35
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false